// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYjbTxGOmD6QMCynPLF18qfBjhGUVvC0',
    appId: '1:811064205660:web:66f8ca3f78a257f5326199',
    messagingSenderId: '811064205660',
    projectId: 'chat-app-d877c',
    authDomain: 'chat-app-d877c.firebaseapp.com',
    storageBucket: 'chat-app-d877c.appspot.com',
    measurementId: 'G-E2WZYS18SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoRA1hnmzcc6DgYVBVig3d9wjfPIfs9ko',
    appId: '1:811064205660:android:c88c0c8d3fddb9f0326199',
    messagingSenderId: '811064205660',
    projectId: 'chat-app-d877c',
    storageBucket: 'chat-app-d877c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqHrDMVuZUmpBlGtKZ7vTHx1jr2pxSHvY',
    appId: '1:811064205660:ios:8d847efde425baee326199',
    messagingSenderId: '811064205660',
    projectId: 'chat-app-d877c',
    storageBucket: 'chat-app-d877c.appspot.com',
    iosClientId: '811064205660-g4r7ri1r5m5u29273qa1qjeuf49pi6s0.apps.googleusercontent.com',
    iosBundleId: 'com.appchat.chatAppFlutter',
  );
}
